mysite/urls.py
from django.urls import path
from django.contrib import admin
import myapp.views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blogs/", v.blogs, name="blogs"),
    path('blogs/<str:topic>/', v.blogs, name='blogs_topic'),
    path("about/", v.about, name="about"),
    path("", v.blogs),
    path("login_view/", v.login_view, name="login_view"),
    path("comment/", v.comment),
    path("create/", v.create, name="create"),
    path("update/", v.update),
    path("delete/", v.delete),
    path("profile/", v.profile, name="profile"),
    path("change_password/", v.change_password),
    path("register/", v.register, name="register"),
    path("logout_view/", v.logout_view, name="logout_view"),
    path("<slug:slug>/", v.show_one_blog, name="show_one_blog")
]

myapp/models.py
from django.db import models
from django.utils.text import slugify
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User

class TopicManager(models.Manager):
    def first_three(self):
        return self.all()[:3]

class TopicManager(models.Manager):
    def first_three(self):
        return self.all()[:3]


class Topic(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    objects = TopicManager()

    def __str__(self):
        return self.title


class Post(models.Model):
    user = models.ForeignKey(User, related_name="user_posts", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    topic = models.ManyToManyField(Topic, related_name="related_posts",
                                   validators=[MinLengthValidator(1, message="At least one topic is required.")])

    @property
    def short_description(self):
        return ' '.join(self.content.split()[:50]) + '...'

    def save(self, *args, **kwargs):
        if self.created_at:
            self.slug = slugify(self.title + '-' + str(self.created_at.date()))
        else:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    user = models.ForeignKey(User, related_name="user_comments", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="post_comments", on_delete=models.CASCADE)

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post, Topic


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=30)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            self.add_error('confirm_password', 'Паролі не збігаються')
        if User.objects.filter(username=username).exists():
            self.add_error('username', 'Користувач з таким ім\'ям вже існує')



class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if User.objects.filter(username=username).exists():
            user = User.objects.get(username=username)
            if not user.check_password(password):
                self.add_error('password', 'Пароль невірний')
        else:
            self.add_error('username', 'Користувача з таким ім\'ям не існує')


class CreatePostForm(forms.Form):
    title = forms.CharField(max_length=50)
    text = forms.CharField(widget=forms.Textarea)
    topic = forms.ModelChoiceField(queryset=Topic.objects.all())


class CommentForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

myapp/views.py
from django.http import HttpResponse
from .models import Post, Topic, Comment
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .forms import RegistrationForm, LoginForm, CreatePostForm, CommentForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


@login_required(login_url='/login_view/')
def blogs(request, topic=None):
    search = request.GET.get('search')
    topics = Topic.objects.all()
    if search:
        posts = Post.objects.filter(title__icontains=search)
    elif topic:
        topic = Topic.objects.get(title=topic)
        posts = Post.objects.filter(topic=topic.id)
    else:
        posts = Post.objects.all()
    return render(request, 'blogs.html', {'posts': posts, 'topics': topics})


@login_required(login_url='/login_view/')
def about(request):
    return HttpResponse("Потенциально тут будет страница с описанием нашего блога.")


@login_required(login_url='/login_view/')
def show_one_blog(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            user = request.user
            text = form.cleaned_data.get('text')
            Comment.objects.create(user=user, post=post, content=text)
            form = CommentForm()
    else:
        form = CommentForm()

    return render(request, 'about_blog.html', {'post': post, 'form': form})


@login_required(login_url='/login_view/')
def comment(request):
    return HttpResponse("Урл для добавления коментария к посту.")


@login_required(login_url='/login_view/')
def create(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('text')
            topic = form.cleaned_data.get('topic')
            post = Post.objects.create(user=user, title=title, content=content)
            post.topic.add(topic)
            return redirect('blogs')
    else:
        form = CreatePostForm()
    return render(request, 'create_post.html', {'form': form})


@login_required(login_url='/login_view/')
def update(request):
    return HttpResponse("Обновление существующего поста")


@login_required(login_url='/login/')
def delete(request):
    return HttpResponse("Удаление поста")


@login_required(login_url='/login_view/')
def profile(request):
    user = request.user
    return render(request, 'profile.html', {'user': user})


@login_required(login_url='/login_view/')
def change_password(request):
    return HttpResponse("Страничка для смены пароля")


def register(request):
    form = RegistrationForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = User.objects.create_user(username=username, email=email, password=password)
            user.save()
            return redirect('login_view')
    else:
        form = RegistrationForm()

    return render(request, 'registration.html', {'form': form})


def login_view(request):
    form = LoginForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('profile')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

@login_required(login_url='/login_view/')
def logout_view(request):
    logout(request)
    return redirect('login_view')

templates/about_blog.html
{% extends 'base.html' %}

{% block content %}
    {% include 'panel_for_registered.html' %}
    <h2>{{ post.title }}</h2>
    <p>Автор: {{ post.user }}</p>
    <p>Дата створення: {{ post.created_at }}</p>
    <p>Зачеплені теми:</p>
        <ul>
            {% for topic in post.topic.all %}
                <li>{{ topic.title }}</li>
            {% endfor %}
        </ul>
    <p>{{ post.content }}</p>
    <h3>Коментарі:</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Відправити</button>
    </form>
        <ul>
            {% for comment in post.post_comments.all %}
                <li>{{ comment.content }} (від {{ comment.user }})</li>
            {% endfor %}
        </ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        input[type="submit"] {
            background-color: hotpink;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        input[type="password"] {
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
            border: none;
        }
        input[type="text"] {
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
            border: none;
        }
        input[type="email"] {
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 5px;
            border: none;
        }
        .btn {
            display: inline-block;
            background: hotpink;
            color: #fff;
            padding: 10px;
            text-decoration: none;
            border-radius: 5px;
        }
        .posts_section{
            background-color: white;
            margin-bottom: 20px;
            padding: 10px;
            box-shadow: 0 0 5px rgba(0,0,0,0.3);
            border-radius: 5px;
        }
        a{
            color: hotpink;
        }
    </style>
</head>
<body style="background-color: lavenderblush">
    {% if user.is_authenticated %}
        {% block panel_for_registered %}
        {% endblock %}
    {% else %}
        {% block panel_for_unregistered %}
        {% endblock %}
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>

templates/blogs.html
{% extends 'base.html' %}

{% block content %}
    {% include 'panel_for_registered.html' %}
    {% for topic in topics %}
        <p><a href="{% url 'blogs_topic' topic=topic.title %}">{{ topic.title }}</a></p>
    {% endfor %}
    <form method="get" action="{% url 'blogs' %}">
        <input type="text" name="search" placeholder="Search...">
        <button type="submit">Search</button>
    </form>
  <h1>List of posts</h1>
  <ul>
    {% for post in posts %}
        <div class="posts_section">
            <a href="{% url 'show_one_blog' slug=post.slug %}">{{ post.title }}</a>
            <p>Дата створення: {{post.created_at}}</p>
            <p>Теми: {{ post.topic.first_three|join:', ' }}</p>
            <p>{{ post.short_description }}</p>
            <p>Коментарів: {{ post.num_comments }}</p>
        </div>
    {% endfor %}
  </ul>
{% endblock %}

templates/create_post.html
{% extends 'base.html' %}

{% block content %}
    {% include 'panel_for_registered.html' %}
    <h1 style="margin-bottom: 30px;">Створити пост</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Опублікувати</button>
    </form>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
    {% include 'panel_for_unregistered.html' %}
	<form method="post">
        {% csrf_token %}
        <h1 style="margin-bottom: 30px;">Login</h1>
        {{ form.as_p }}
        <button type="submit">Увійти</button>
	</form>
    <a href="{% url 'register' %}">Ще не зареєстровані?</a>
{% endblock %}

templates/panel_for_registered.html
<div style="padding: 20px; background-color: hotpink; border-radius: 5px">
    <a href="{% url 'blogs' %}" class="btn">Головна   </a>
    <a href="{% url 'create' %}" class="btn">Створити пост   </a>
    <a href="{% url 'profile' %}" class="btn">Моя сторінка</a>
    <a href="{% url 'logout_view'%}" class="btn">вийти</a>
</div>

templates/panel_for_unregistered.html
<div style="padding: 20px; background-color: hotpink; border-radius: 5px">
    <a href="{% url 'login_view' %}" class="btn">login   </a>
    <a href="{% url 'register' %}" class="btn">register   </a>
</div>

templates/profile.html
{% extends 'base.html' %}

{% block content %}
    {% include 'panel_for_registered.html' %}
    <h2>Профіль користувача {{ user.username }}</h2>
    <p>Email: {{ user.email }}</p>
    <p>Кількість публікацій: {{ user.post_set.count }}</p>
    <h3>Список публікацій</h3>
    <ul>
        {% for post in user.post_set.all %}
            <li><a href="{% url 'show_one_blog' post.slug %}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% block content %}
    {% include 'panel_for_unregistered.html' %}
    <h1 style="margin-bottom: 30px;">Реєстрація</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">зареєструватися</button>
    </form>
    <a href="{% url 'login_view' %}">Вже зареєстровані?</a>
{% endblock %}

templates/topic_list.html
<ul>
{% for topic in topic_list %}
    <li><a href="{% url 'blogs_topic' topic_name=topic.title %}">{{ topic.title }}</a></li>
{% endfor %}
</ul>